#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dtests=false \
    -Dvulkan=enabled \
    -Dglslang=enabled \
    -Dshaderc=enabled \
    -Dlcms=disabled \
    -Ddemos=false \
    . output

ninja -C output
ninja -C output install
