#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_ISNTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DLIBICAL_BUILD_TESTING=false \
    -DLIBICAL_JAVA_BINDINGS=false \
    -DLIBICAL_BUILD_DOCS=false \
    -DLIBICAL_GLIB=true \
    -DGOBJECT_INTROSPECTION=true \
    -Wno-dev

cmake --build   build
cmake --install build
