#!/bin/sh -e

export DESTDIR="$1"

sed -i -e '/examples/d;/third_party/d' CMakeLists.txt
sed -i -e '/build-version/d' glslc/CMakeLists.txt
cat <<- EOF > glslc/src/build-version.inc
    "shaderc 2021.0\n"
    "SPIRV-Tools-2021.1\n"
    "glslang-11.4.0\n"
EOF

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DSHADERC_SKIP_TESTS=ON \
    -Dglslang_SOURCE_DIR=/usr/include/glslang

cmake --build   build
cmake --install build
