#!/bin/sh -e

patch -p1 < nettle-4.patch

./configure \
    --prefix=/usr \
    --disable-nls \
    --disable-metalink \
    --disable-websocket \
    --without-libxml2 \
    --without-libexpat \
    --without-sqlite3

make
make DESTDIR="$1" install
