#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < freerdp-3.9.0-NTLM_fixes.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=OFF \
    -DCHANNEL_URBDRC=OFF \
    -DWITH_ALSA=ON \
    -DWITH_CCACHE=OFF \
    -DWITH_DEBUG_ALL=OFF \
    -DWITH_MANPAGES=OFF \
    -DWITH_FFMPEG=ON \
    -DWITH_SWSCALE=ON \
    -DWITH_CAIRO=ON \
    -DWITH_DSP_FFMPEG=ON \
    -DWITH_GSTREAMER_1_0=OFF \
    -DWITH_NEON=OFF \
    -DWITH_JPEG=ON \
    -DWITH_OPENH264=OFF \
    -DWITH_PULSE=OFF \
    -DWITH_SERVER=ON \
    -DWITH_PCSC=OFF \
    -DWITH_LIBSYSTEMD=OFF \
    -DWITH_KRB5=OFF \
    -DWITH_FUSE=ON \
    -DWITH_X11=ON \
    -DWITH_XINERAMA=ON \
    -DWITH_XV=ON \
    -DWITH_WAYLAND=OFF

cmake --build   build
cmake --install build
