#!/bin/sh -e

export CFLAGS="$CFLAGS -D_LARGEFILE64_SOURCE"

./configure \
    --prefix=/usr \
    --disable-nls \
    --disable-gpg-test

make
make DESTDIR="$1" install

# Ensure that gpgme-config is always installed
cp -f src/gpgme-config "$1/usr/bin/"
