#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < rapidjson-fix-non-compiling-assignment-operator.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_CXX_COMPILER=clang++

cmake --build   build
cmake --install build
