#!/bin/sh -e

export RUSTUP_TOOLCHAIN=stable
export CARGO_TARGET_DIR=target

cargo fetch --locked --target x86_64-unknown-linux-gnu

cd qobuz-player-web
npm install
npm run build

cd ..
cargo build --frozen --release --all-features

mkdir -p "$1/usr/bin"
cp target/release/qobuz-player "$1/usr/bin/"
