#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    output

ninja -C output
ninja -C output install

mkdir -p "$1/etc/sv/mpdscribble"
cp -f mpdscribble.run "$1/etc/sv/mpdscribble/run"
ln -sf /run/runit/supervise.mpdscribble "$1/etc/sv/mpdscribble/supervise"
