#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < spirv-tools-2020.5-build-against-spirv-headers-1.5.4.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DSPIRV_WERROR=OFF \
    -DSPIRV-Headers_SOURCE_DIR=/usr

cmake --build   build
cmake --install build
