#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < install-static-libs.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DALLOW_EXTERNAL_SPIRV_TOOLS=1

cmake --build   build
cmake --install build
