#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

for p in *.patch; do
    patch -p1 < "$p"
done

make \
    prefix=/usr \
    shared=yes \
    build=release \
    USE_SYSTEM_LIBS=yes \
    HAVE_X11=no \
    HAVE_GLUT=no \
    install

ln -s libmupdf.so "$1/usr/lib/libmupdf.so.0"
