#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dalsa=enabled \
    -Ddbus=disabled \
    -Dsystemd=disabled \
    -Dtest=false \
    -Dzeroconf=disabled \
    output

ninja -C output
ninja -C output install

mkdir -p "$1/etc/sv/mpd"
cp -f mpd.run "$1/etc/sv/mpd/run"
ln -sf /run/runit/supervise.mpd "$1/etc/sv/mpd/supervise"
