#!/bin/sh -e

export PKG_CONFIG_PATH="/usr/lib/pkgconfig"
export PATH="$PATH:llvm-mingw/bin"

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --with-x \
    --with-mingw \
    --enable-win64 \
    --enable-archs=i386,x86_64

make
make prefix="$1/usr" libdir="$1/usr/lib" dlldir="$1/usr/lib/wine" install
